### ISSUE TITLE
감자들의 첫 Issue

### ISSUE THREAD

**Issue by K-moovie** [boostcampwm-2021/web18-BooStore#1]
## 목적
📢 아아 이슈테스트

## 작업 내용
- [x] 이슈 생성
- [x] 이슈 등록
- [x] 이슈 마감
- [x] 칸반보드 사용

## 주의사항
- 안될 수 도 있음!!!

**Comment by gidskql6671** [comment]
![부스트캠프 메인 GIF](https://user-images.githubusercontent.com/23000498/144479828-ba888e0b-3470-4a66-8bd4-51fe5e5a51ea.gif)
