### ISSUE TITLE
CI/CD 환경 구축 

### ISSUE THREAD

**Issue by K-moovie** [boostcampwm-2021/web18-BooStore#9]
## 목적
프로젝트의 CI/CD 환경을 구축한다.
## 작업 내용
- [x] nCloud 파이프라인 구축
- [x] nCloud 서버 구축
- [x] Docker 설치 및 스크립트 파일 작성
- [x] Nginx 설치 및 스크립트 파일 작성

## 주의사항
당황하지 말 것!

**Comment by gidskql6671** [comment]
![CI CD](https://user-images.githubusercontent.com/23000498/144384721-f23f2673-fe68-4150-8926-72b907e23259.png)
![무중단 배포](https://user-images.githubusercontent.com/23000498/144384729-a63de62c-6ddf-4d56-a7dc-480f891b94fc.png)
